import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { formatCurrency, formatDate } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function PublicContractView({ params }: { params: { token: string } }) {
  const contract = await db.contract.findUnique({
    where: { shareToken: params.token },
    include: { property: true, client: true },
  });
  if (!contract) notFound();

  return (
    <main className="min-h-screen bg-bg-canvas">
      <div className="mx-auto max-w-marketing px-space-6 py-space-9">
        <p className="eyebrow mb-space-2">Real Estate OS · Shared contract</p>
        <h1 className="text-display-lg mb-space-2">{contract.property.title}</h1>
        <p className="text-body-lg text-ink-secondary mb-space-7">
          {contract.property.address} · {contract.property.city}/{contract.property.state}
        </p>

        <div className="rounded-card border border-border-hair bg-bg-surface p-space-6">
          <dl className="grid grid-cols-2 gap-y-space-4 gap-x-space-6">
            <Item label="Type" value={contract.kind} mono={false} capitalize />
            <Item label="Status" value={contract.status} mono={false} capitalize />
            <Item label="Start" value={formatDate(contract.startDate)} />
            <Item label="End" value={contract.endDate ? formatDate(contract.endDate) : "—"} />
            <Item label="Total" value={formatCurrency(contract.totalCents / 100)} />
            {contract.monthlyCents ? <Item label="Monthly" value={formatCurrency(contract.monthlyCents / 100)} /> : null}
            <div className="col-span-2">
              <dt className="text-caption uppercase tracking-[0.08em] text-ink-secondary mb-space-1">Client</dt>
              <dd className="text-body">{contract.client.name}</dd>
            </div>
            {contract.notes ? (
              <div className="col-span-2">
                <dt className="text-caption uppercase tracking-[0.08em] text-ink-secondary mb-space-1">Notes</dt>
                <dd className="text-body whitespace-pre-wrap">{contract.notes}</dd>
              </div>
            ) : null}
          </dl>
        </div>

        <p className="text-body-sm text-ink-secondary mt-space-6">
          This is a read-only public view of contract <span className="font-mono">{contract.id.slice(0, 8)}</span>.
          Generated by Real Estate OS.
        </p>
      </div>
    </main>
  );
}

function Item({ label, value, mono = true, capitalize = false }: { label: string; value: string; mono?: boolean; capitalize?: boolean }) {
  return (
    <div>
      <dt className="text-caption uppercase tracking-[0.08em] text-ink-secondary mb-space-1">{label}</dt>
      <dd className={`text-body ${mono ? "font-mono font-tabular" : ""} ${capitalize ? "capitalize" : ""}`}>{value}</dd>
    </div>
  );
}
